### ISSUE TITLE
Repeat input dependent generators

### ISSUE THREAD

**Issue by assignUser** [hedgehogqa/r-hedgehog#12]
Hello!

First off: thank you for you work on this package! I am very new to using tests and property testing specifically, so in case I am doing something obviously wrong or using a faulty approach please let me know. I also only have the tiniest bit of knowledge about FP (aka some YT vids and some lyah), but I find it fascinating and useful and want to learn more.  

I will try to explain my issue/what I want to do as simply as possible, should you want to check out the whole thing you can find it [here](https://github.com/assignUser/simstudy/blob/more-tests/tests/testthat/helper-gen_def.R). 

I am currently trying to bring property testing to the package [simstudy](https://github.com/kgoldfeld/simstudy), big part of the package workflow is the creation of definition tables like this: 
```r
def <- defData(varname = "nr", dist = "nonrandom", formula = 7, id = "idnum")
def <- defData(def, varname = "x1", dist = "uniform", formula = "10;20")
def <- defData(def, varname = "y1", formula = "nr + x1 * 2", variance = 8)
```
The sane person I am I choose this function as my first target for property testing, instead of some small internal function. 😅 It worked out pretty good for a first try, composing all the generators to create the different arguments for `defData` was very smooth with hedgehog!

My issue is now that I can not use something like `gen.and_then(gen.int(50), function(n) gen.list(of = n,gen_def))`
because the validity of the 2nd, ... ,nth call to `defData` are dependent on the state of the definition table up to that point (e.g. can't use previously defined varnames, formula CAN use previously defined vars, etc.).

And this brings me to my actual question: Is there a "correct"/idiomatic way to loop over a generator an arbitrary number of times and feed its output as the next iterations input? I tried it with a normal for loop but that doesn't work for generators as I found out. My "solution" was the following code which works fine with `gen.example` but runs into the "unreachable" branch when run using `forall` in a `test_that`: 

```r
gen_def_1row <-gen.and_then(gen_def_dt_n,function(dt)gen_def_fst(dt))
gen_def_loop <- function(res) {
  dif <- nrow(res$dt) - nrow(res$def)
  
  if (dif > 1)
    gen.and_then(gen_def_nth(res), function(res)
      gen_def_loop(res))
  else if (dif == 1)
    gen.map(function(res)
      res$def, gen_def_nth(res))
  else
    stop("This should never be reached")
}
gen_def <- gen.and_then(gen_def_1row,function(res) gen_def_loop(res))
``` 
Thanks again!

**Comment by HuwCampbell** [comment]
Hi, Thanks!
I'm looking into this for you. I'm not really familiar with simstudy, but, I'll try to get back to you properly within a few days.

`gen.and_then` can use the result of a computed to construct a new generator, as I'm sure you've noticed.

If that's not powerful enough, then the state machine testing support should cover essentially everything you might want to try.

**Comment by assignUser** [comment]
Hey,

over the last few days I continued to work with generators, very powerful indeed! I also  think I "know" what the issue is with the above code: ` dif <- nrow(res$dt) - nrow(res$def)`  due to the way you unfold generators (which looks like magic to me 😲) any time one tries to access the **explicit** result of a generator within a generator that is not the _very last layer_ it causes undefined behavior.  

I think I should be able to do something similar to this generator mentioned above now: `gen.and_then(gen.int(50), function(n) gen.list(of = n,gen_def))`, it is just seems to be important that all generators I want to have access `n` need to be in the scope of the first gen.and_then  explicitly and not just called via variable. Otherwise they wont have access to `n`.  

That probably is again due to how the generators are unfolded and R scoping rules that I am not to sure about in this case. maybe using `force()` to force evaluation would also be possible? not sure.

But this gave me an idea for a feature: Make it possible set a custom environment for generators. Maybe `gen.env(envir = new.env())` that can wrap a bunch of generators /first in a chain, to set the environment used there after. I would try to do a PR but my grasp one the concepts used is not nearly good enough to even get started 😆 . 

State machine testing also looks very interesting, have to look into that too!

**Comment by assignUser** [comment]
Ok, so I have done quite a bit (~40 tests) with r-Hedgehog the last days and found sum bugs, which is great!

I thought I managed to get the issue resolved with the input dependent generators ~~but it still only works for examples (probably because shrinks are not calculated for examples?)~~ It just runs reealllly long when wrapped in `gen.sized`. I think I should look into using the state machine testing for the big stuff which are basically integration tests and not unit tests anyway. 

Just for posterity's sake: I solved it by using external size/counter variables instead of inferring them from the generated object (e.g. `nrow(dt)`) :
```r
gen_def <- gen.and_then(gen.int(20),function(n) gen.and_then(gen_def_dt(n),function(dt) gen_defs(dt,n,1)))

gen_defs <- function(dt,n,i = 1){
  if(i > n) return(dt)
  generate(for  (x in stuff)
    [assign stuff to dt cells]
    gen_defs(dt,n,i+1) )
  }
```

**Comment by HuwCampbell** [comment]
That's great, glad you're finding and fixing some bugs.

It looks like you've written something similar to `gen.recursive`; you might want to look into using that if it makes the code easier to maintain.

If you want to, you can share a slow example and I can profile it. `gen.sized` doesn't really do very much, so I doubt that that's the slow bit.

The state machine testing is great when there's effectful systems to test; so yes, for integration testing it should be ideal.

**Comment by assignUser** [comment]
Thanks for the tip `gen.recursive` looks handy! 

I think the generator I  composed is just very complex and big (amongst other things it creates and assign arbitrary variables and functions).  I can't really post a slow example in a short form. The issue  I had was with this line 
```r
gen_def <- gen.and_then(gen.int(20),function(n) gen.and_then(gen_def_dt(n),function(dt) gen_defs(dt,n,1)))
``` 
(from [here](
https://github.com/assignUser/simstudy/blob/2c5d23203895045ff10c563116c1cc6ae3425d78/tests/testthat/helper-gen_def.R), I am open for any suggestions ^-^) When wrapped in `gen.size` instead of `gen.and_then(gen.int(20)` it took several minutes to finish and really bogged down my R session. With the current version the test still takes several seconds but works 😁

I skimmed the state machine vignette and have some general questions: currently I mainly use generators to run tests with valid inputs and use boring example based tests to check errors and warnings because I would need to write new generators for each error/warning and I don't feel that that'd be worth it. (e.g. [here](https://github.com/assignUser/simstudy/blob/2c5d23203895045ff10c563116c1cc6ae3425d78/tests/testthat/test-int_evalDef.R#L43)) Is that sensible? 

Or how would you approach that?  With my limited knowledge I guess that's an issue with using errors/warnings instead of returning a value? 

What I watched/read about property based testing was pretty much exclusively concerned with testing valid inputs and not failures, so I'm pretty unsure about this. I would be glade about any feedback but do of course understand if you don't have the time to get into it.

Thanks again!

**Comment by assignUser** [comment]
Best done with state machine, with the caveat laid out in #16  for unique varnames.
Maybe it is possible to memoize a larg list of unique names for the generator, as it is non shrinking anyway.

If you have any more Input I would be happy to receive it but will close this issue, as the actual question is solved.
