### ISSUE TITLE
is_lang depreacted as of rlang 0.2.0

### ISSUE THREAD

**Issue by assignUser** [hedgehogqa/r-hedgehog#14]
Hey just noticed this while creating a reprex:
```r
gen_digit_list <- gen.sized(function(n) gen.c(gen.int(9),of = n))
gen_squares   <- generate(for (i in gen_digit_list) data.frame(d = i, s = i^2))
#> Warning: `is_lang()` is deprecated as of rlang 0.2.0.
#> Please use `is_call()` instead.
#> This warning is displayed once per session.
```
Not sure if you use it any where other than here: https://github.com/hedgehogqa/r-hedgehog/blob/2884bdbd02adb018440bae61ac6e89bb9a6602cc/R/gen.R#L105

**Comment by HuwCampbell** [comment]
Thank you.

Yeah probably not. I tried to use as little reflection as possible while writing. The `for` trick was suggested to make things a bit easier after the core was fleshed out.

I'm very happy to take and test a PR on that one if it gets us off a deprecated function.
