### ISSUE TITLE
command$require - State Machine Testing

### ISSUE THREAD

**Issue by assignUser** [hedgehogqa/r-hedgehog#16]
Hello again!

I started to implement the input dependent stuff as a state machine, which works and is easier! 
But I came across an issue with the require`function for commands, maybe I did not understand the reason for this function. 

It is there to test preconditions of state and generated inputs to keep everything valid. I thought it would discard commands with invalid inputs but instead it kills the entire test with `stop("Command generation arguments voilate requirements")` (typo is fixed in my pr 😉 )

My generator creates random variable names and these need to be unique, so I thought defining the require to return false when the name is already present (which happen very rarely mostly with single character names, an obvious fix would be to increase min length but I would like to understand the principle here), is this not what require is for?
```r
initialmodel <- list(def = NULL, varnames = character(0) , data= NULL)
addVar <- command(
  "Add Variable",
  generator = function(state) {
    gen.and_then(gen_dist, function(dist)
      list(
        def = state$def,
        varname = gen.no.shrink(gen_varname),
        dist = dist,
        formula = get(reg[name == dist, ]$formula)(state$varnames),
        variance = get(reg[name == dist, ]$variance)(state$varnames),
        link = get(reg[name == dist, ]$link)
      ))
  },
  #preconditions
  require = function(state, def , varname, ...) {
     if (is.null(state$def))
      TRUE
    else
      ! varname %in% state$varnames
  }
[...]
```

**Comment by assignUser** [comment]
I had a look through the code for `gen.actions` and am now sure that I did understand require correctly but missed a crucial point in its application. Any conditions resulting in require returning false also **have** to return `NULL` from gen, otherwise non applicable actions are picked bei the generator and the error above is the result (which is mentioned in the documentation). 

But the conditions can **only** depend on state and not on generated inputs as those are not final until the list of actions is passed to `expect_sequential`.  With the code above this led to actions being dropped by `drop.invalid` due to changed generated inputs when passed to `expect_sequential`, which in turn led to a mix up with the symbolic output variables (e.g. action1$output = 1, action2$input = symbolic 3 ⚡ 🛑 ).

As far as I understand the code, dropping actions due to invalid generated inputs is not possible (except during shrinking? but only for conditions that are 100% true with un shrunk values?) and the attempt will lead to undefined behavior.

**Comment by HuwCampbell** [comment]
That sounds correct.

When shrinking in state machine testing, we drop actions randomly, but we want to make sure that it would have been _possible_ to generate subsequent actions had the dice fallen that way originally. And that's all the `require` is for. On the first pass (before any shrinking, the requires should always be true).
