### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by hadley** [hedgehogqa/r-hedgehog#3]
I think modern best practice broadly recommends that you use `_` instead of `.`, reserving `.` for separating S3 generics and classes. It also feels weird to not use `_` in `forall`.  So I'd write:

```R
  forall( list( as = gen.c( gen.element(1:100) )
              , bs = gen.c( gen.element(1:100) ))
        , function(as,bs) expect_equal ( rev(c(as, bs)), c(rev(bs), rev(as)))
  )
```

as

```R
for_all(
  list(
    as = gen_c(gen_element(1:100)),
    bs = gen_c(gen_element(1:100))
  ), 
  function(as, bs) expect_equal(rev(c(as, bs)), c(rev(bs), rev(as)))
)
```

(but I'm not sure why you need `gen_c()` here)

**Comment by HuwCampbell** [comment]
I've followed through on all of these except for the `gen` functions. This is mostly for consistency with the hedgehog ecosystem, which encourages the same semantics across different libraries.

**Comment by HuwCampbell** [comment]
Thanks for the advice :)
